# Generated by Django 6.0.1 on 2026-01-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TruongDaiHoc",
            fields=[
                (
                    "matruong",
                    models.CharField(
                        db_column="MATRUONG",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tentruong", models.CharField(db_column="TENTRUONG", max_length=200)),
                (
                    "loaitruong",
                    models.CharField(
                        blank=True, db_column="LOAITRUONG", max_length=50, null=True
                    ),
                ),
                (
                    "logo",
                    models.CharField(
                        blank=True, db_column="LOGO", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "TRUONGDAIHOC",
                "managed": False,
            },
        ),
    ]
