# Generated by Django 6.0.1 on 2026-04-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChiTietNganh",
            fields=[
                (
                    "mactn",
                    models.CharField(
                        db_column="MACTN",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hocphi",
                    models.IntegerField(blank=True, db_column="HOCPHI", null=True),
                ),
                (
                    "thoigianhoc",
                    models.IntegerField(blank=True, db_column="THOIGIANHOC", null=True),
                ),
            ],
            options={
                "db_table": "CHITIETNGANH",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChiTietTruong",
            fields=[
                (
                    "mactt",
                    models.CharField(
                        db_column="MACTT",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mota", models.TextField(blank=True, db_column="MOTA", null=True)),
                (
                    "ghichu",
                    models.CharField(
                        blank=True, db_column="GHICHU", max_length=300, null=True
                    ),
                ),
            ],
            options={
                "db_table": "CHITIETTRUONG",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DiemChuan",
            fields=[
                (
                    "madiem",
                    models.CharField(
                        db_column="MADIEM",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nam", models.IntegerField(db_column="NAM")),
                ("diem", models.FloatField(blank=True, db_column="DIEM", null=True)),
                (
                    "khoixt",
                    models.CharField(
                        blank=True, db_column="KHOIXT", max_length=20, null=True
                    ),
                ),
                (
                    "ghichu",
                    models.CharField(
                        blank=True, db_column="GHICHU", max_length=200, null=True
                    ),
                ),
            ],
            options={
                "db_table": "DIEMCHUAN",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DonViHanhChinh",
            fields=[
                (
                    "madvhc",
                    models.CharField(
                        db_column="MADVHC",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tendvhc", models.CharField(db_column="TENDVHC", max_length=100)),
                (
                    "loai",
                    models.CharField(
                        blank=True, db_column="LOAI", max_length=30, null=True
                    ),
                ),
            ],
            options={
                "db_table": "DONVIHANHCHINH",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HinhAnhNganh",
            fields=[
                (
                    "mahinh_nganh",
                    models.CharField(
                        db_column="MAHINH_NGANH",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenfile", models.CharField(db_column="TENFILE", max_length=255)),
                (
                    "tieude",
                    models.CharField(
                        blank=True, db_column="TIEUDE", max_length=200, null=True
                    ),
                ),
                ("mota", models.TextField(blank=True, db_column="MOTA", null=True)),
                (
                    "ngaytao",
                    models.DateTimeField(blank=True, db_column="NGAYTAO", null=True),
                ),
            ],
            options={
                "db_table": "HINHANH_NGANH",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HinhAnhTruong",
            fields=[
                (
                    "mahinh_truong",
                    models.CharField(
                        db_column="MAHINH_TRUONG",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenfile", models.CharField(db_column="TENFILE", max_length=255)),
                (
                    "tieude",
                    models.CharField(
                        blank=True, db_column="TIEUDE", max_length=200, null=True
                    ),
                ),
                ("mota", models.TextField(blank=True, db_column="MOTA", null=True)),
                (
                    "ngaytao",
                    models.DateTimeField(blank=True, db_column="NGAYTAO", null=True),
                ),
            ],
            options={
                "db_table": "HINHANH_TRUONG",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="KetQuaKhaoSat",
            fields=[
                (
                    "makq",
                    models.CharField(
                        db_column="MAKQ",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("diemtu", models.IntegerField(db_column="DIEMTU")),
                ("diemden", models.IntegerField(db_column="DIEMDEN")),
                (
                    "mota",
                    models.CharField(
                        blank=True, db_column="MOTA", max_length=200, null=True
                    ),
                ),
            ],
            options={
                "db_table": "KETQUAKHAOSAT",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="KhaoSat",
            fields=[
                (
                    "maks",
                    models.CharField(
                        db_column="MAKS",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cauhoi", models.CharField(db_column="CAUHOI", max_length=400)),
                (
                    "hinhanh",
                    models.CharField(
                        blank=True, db_column="HINHANH", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "KHAOSAT",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LuaChonKhaoSat",
            fields=[
                (
                    "malc",
                    models.CharField(
                        db_column="MALC",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("noidung", models.CharField(db_column="NOIDUNG", max_length=300)),
                ("diem", models.IntegerField(db_column="DIEM")),
            ],
            options={
                "db_table": "LUACHONKHAOSAT",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NganhHoc",
            fields=[
                (
                    "manganh",
                    models.CharField(
                        db_column="MANGANH",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tennganh", models.CharField(db_column="TENNGANH", max_length=200)),
                (
                    "linhvuc",
                    models.CharField(
                        blank=True, db_column="LINHVUC", max_length=100, null=True
                    ),
                ),
                ("mota", models.TextField(blank=True, db_column="MOTA", null=True)),
            ],
            options={
                "db_table": "NGANHHOC",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NguoiDung",
            fields=[
                (
                    "mand",
                    models.CharField(
                        db_column="MAND",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hoten", models.CharField(db_column="HOTEN", max_length=150)),
                (
                    "email",
                    models.EmailField(db_column="EMAIL", max_length=100, unique=True),
                ),
                (
                    "sodienthoai",
                    models.CharField(
                        db_column="SODIENTHOAI", max_length=15, unique=True
                    ),
                ),
                (
                    "tendangnhap",
                    models.CharField(
                        db_column="TENDANGNHAP", max_length=50, unique=True
                    ),
                ),
                ("matkhau", models.CharField(db_column="MATKHAU", max_length=255)),
                (
                    "trangthai",
                    models.CharField(
                        db_column="TRANGTHAI", default="HOATDONG", max_length=20
                    ),
                ),
                (
                    "ngaytao",
                    models.DateTimeField(blank=True, db_column="NGAYTAO", null=True),
                ),
            ],
            options={
                "db_table": "NGUOIDUNG",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TinhThanh",
            fields=[
                (
                    "matinh",
                    models.CharField(
                        db_column="MATINH",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tentinh", models.CharField(db_column="TENTINH", max_length=100)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TruongDaiHoc",
            fields=[
                (
                    "matruong",
                    models.CharField(
                        db_column="MATRUONG",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tentruong", models.CharField(db_column="TENTRUONG", max_length=200)),
                (
                    "loaitruong",
                    models.CharField(
                        blank=True, db_column="LOAITRUONG", max_length=50, null=True
                    ),
                ),
                ("diachi", models.TextField(blank=True, db_column="DIACHI", null=True)),
                (
                    "website",
                    models.CharField(
                        blank=True, db_column="WEBSITE", max_length=255, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="EMAIL", max_length=100, null=True
                    ),
                ),
                (
                    "dienthoai",
                    models.CharField(
                        blank=True, db_column="DIENTHOAI", max_length=30, null=True
                    ),
                ),
                ("lat", models.FloatField(blank=True, db_column="LAT", null=True)),
                ("lng", models.FloatField(blank=True, db_column="LNG", null=True)),
            ],
            options={
                "db_table": "TRUONGDAIHOC",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VaiTro",
            fields=[
                (
                    "mavaitro",
                    models.CharField(
                        db_column="MAVAITRO",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenvaitro",
                    models.CharField(db_column="TENVAITRO", max_length=50, unique=True),
                ),
                (
                    "mota",
                    models.CharField(
                        blank=True, db_column="MOTA", max_length=200, null=True
                    ),
                ),
            ],
            options={
                "db_table": "VAITRO",
                "managed": False,
            },
        ),
    ]
