# Generated by Django 6.0.1 on 2026-01-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="truongdaihoc",
            options={},
        ),
    ]
