# Generated by Django 6.0.1 on 2026-04-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tinhthanh",
            table="TINHTHANH",
        ),
    ]
