# Generated by Django 6.0.1 on 2026-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_truongdaihoc_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChiTietNganh",
            fields=[
                (
                    "mactn",
                    models.CharField(
                        db_column="MACTN",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hocphi",
                    models.IntegerField(blank=True, db_column="HOCPHI", null=True),
                ),
                (
                    "thoigianhoc",
                    models.IntegerField(blank=True, db_column="THOIGIANHOC", null=True),
                ),
            ],
            options={
                "db_table": "CHITIETNGANH",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChiTietTruong",
            fields=[
                (
                    "mactt",
                    models.CharField(
                        db_column="MACTT",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mota", models.TextField(blank=True, db_column="MOTA", null=True)),
                (
                    "ghichu",
                    models.CharField(
                        blank=True, db_column="GHICHU", max_length=300, null=True
                    ),
                ),
            ],
            options={
                "db_table": "CHITIETTRUONG",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DonViHanhChinh",
            fields=[
                (
                    "madvhc",
                    models.CharField(
                        db_column="MADVHC",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tendvhc", models.CharField(db_column="TENDVHC", max_length=100)),
                (
                    "loai",
                    models.CharField(
                        blank=True, db_column="LOAI", max_length=30, null=True
                    ),
                ),
            ],
            options={
                "db_table": "DONVIHANHCHINH",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HinhAnhNganh",
            fields=[
                (
                    "mahinh_nganh",
                    models.CharField(
                        db_column="MAHINH_NGANH",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenfile", models.CharField(db_column="TENFILE", max_length=255)),
                (
                    "tieude",
                    models.CharField(
                        blank=True, db_column="TIEUDE", max_length=200, null=True
                    ),
                ),
                ("mota", models.TextField(blank=True, db_column="MOTA", null=True)),
                (
                    "ngaytao",
                    models.DateTimeField(blank=True, db_column="NGAYTAO", null=True),
                ),
            ],
            options={
                "db_table": "HINHANH_NGANH",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HinhAnhTruong",
            fields=[
                (
                    "mahinh_truong",
                    models.CharField(
                        db_column="MAHINH_TRUONG",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenfile", models.CharField(db_column="TENFILE", max_length=255)),
                (
                    "tieude",
                    models.CharField(
                        blank=True, db_column="TIEUDE", max_length=200, null=True
                    ),
                ),
                ("mota", models.TextField(blank=True, db_column="MOTA", null=True)),
                (
                    "ngaytao",
                    models.DateTimeField(blank=True, db_column="NGAYTAO", null=True),
                ),
            ],
            options={
                "db_table": "HINHANH_TRUONG",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NganhHoc",
            fields=[
                (
                    "manganh",
                    models.CharField(
                        db_column="MANGANH",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tennganh", models.CharField(db_column="TENNGANH", max_length=200)),
                (
                    "linhvuc",
                    models.CharField(
                        blank=True, db_column="LINHVUC", max_length=100, null=True
                    ),
                ),
                ("mota", models.TextField(blank=True, db_column="MOTA", null=True)),
            ],
            options={
                "db_table": "NGANHHOC",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TinhThanh",
            fields=[
                (
                    "matinh",
                    models.CharField(
                        db_column="MATINH",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tentinh", models.CharField(db_column="TENTINH", max_length=100)),
            ],
            options={
                "db_table": "TINHTHANH",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="truongdaihoc",
            options={"managed": False},
        ),
    ]
